language: php

env:
  - NETTE=default
  - NETTE=~2.2.0

php:
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - php .travis.composer.php
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
  - composer create-project --prefer-source --dev --no-interaction jakub-onderka/php-parallel-lint parallel-lint ~0.8.0

script:
    - php parallel-lint/parallel-lint.php -e php,phpt src tests
    - vendor/bin/tester -s -p php -c tests/php.ini tests
